//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.3
//     from Assets/Modules/Chip Creation/Scripts/Input/Chip Editor Actions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ChipEditorActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ChipEditorActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Chip Editor Actions"",
    ""maps"": [
        {
            ""name"": ""Action Map"",
            ""id"": ""46a31ba3-6e11-47e5-a3a9-a9041b1059fd"",
            ""actions"": [
                {
                    ""name"": ""Toggle Pin Name Display"",
                    ""type"": ""Button"",
                    ""id"": ""8f42c2dc-d07d-4cde-ab9e-86d0c4d8f1c8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""67caf609-d910-4d9c-be34-c51734eacb52"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Toggle Pin Name Display"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""New control scheme"",
            ""bindingGroup"": ""New control scheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Action Map
        m_ActionMap = asset.FindActionMap("Action Map", throwIfNotFound: true);
        m_ActionMap_TogglePinNameDisplay = m_ActionMap.FindAction("Toggle Pin Name Display", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Action Map
    private readonly InputActionMap m_ActionMap;
    private IActionMapActions m_ActionMapActionsCallbackInterface;
    private readonly InputAction m_ActionMap_TogglePinNameDisplay;
    public struct ActionMapActions
    {
        private @ChipEditorActions m_Wrapper;
        public ActionMapActions(@ChipEditorActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @TogglePinNameDisplay => m_Wrapper.m_ActionMap_TogglePinNameDisplay;
        public InputActionMap Get() { return m_Wrapper.m_ActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ActionMapActions set) { return set.Get(); }
        public void SetCallbacks(IActionMapActions instance)
        {
            if (m_Wrapper.m_ActionMapActionsCallbackInterface != null)
            {
                @TogglePinNameDisplay.started -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnTogglePinNameDisplay;
                @TogglePinNameDisplay.performed -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnTogglePinNameDisplay;
                @TogglePinNameDisplay.canceled -= m_Wrapper.m_ActionMapActionsCallbackInterface.OnTogglePinNameDisplay;
            }
            m_Wrapper.m_ActionMapActionsCallbackInterface = instance;
            if (instance != null)
            {
                @TogglePinNameDisplay.started += instance.OnTogglePinNameDisplay;
                @TogglePinNameDisplay.performed += instance.OnTogglePinNameDisplay;
                @TogglePinNameDisplay.canceled += instance.OnTogglePinNameDisplay;
            }
        }
    }
    public ActionMapActions @ActionMap => new ActionMapActions(this);
    private int m_NewcontrolschemeSchemeIndex = -1;
    public InputControlScheme NewcontrolschemeScheme
    {
        get
        {
            if (m_NewcontrolschemeSchemeIndex == -1) m_NewcontrolschemeSchemeIndex = asset.FindControlSchemeIndex("New control scheme");
            return asset.controlSchemes[m_NewcontrolschemeSchemeIndex];
        }
    }
    public interface IActionMapActions
    {
        void OnTogglePinNameDisplay(InputAction.CallbackContext context);
    }
}
